notifications:
  email: false
os: linux
language: python
python: 3.8
install:
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
# install package
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
#- coverage run --source=ckanext setup.py test
#- coverage report -m
- flake8 ckanext
after_success:
- codecov
before_deploy:
#- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: "ci_dcor"
  password:
    secure: "3xfyf+Rm3ZeMjBEqwioLtwVXbt2mocFpxV1EVyoy4OMXDuzrZAmz9q0LAmT9atu/bZRHfLdTuUStvYwJu/KQooptg/8RemktCat4uf+Z6hDYqqU62JE7Pkwg+KrMRc0sK/R/kGZqShc4FriuMpp4/Ij2HzzMbQ9I/EsmXsAYk4MmtR80QZmBLqd359bM+wQrUyXhQ+Xw2w9h0WEAp3HRf4vU0kuka9rTx5FyrpAEyiUBt6bKnH0gslzQZC06W7GVavpMiS6JICIZROeTOQrk7h6AjxGoMy8qc6nqerOpgmfijdJbSi6ke5QaUr1T5no1ShUOQpx68ORSU4DHHDp3spoNQ/7i6u/1jvL2niy7KdtOUItjVkhxdVJtIckSEQ53tzl1gd7Gu3N1GWOvEEUBK92gOgLoTzwty/HkgbY+BnjeevdSfu/gY+AuETYizv7/vi5j7+G86ztzF2yRiLVZYJ/jupHY5VrCGLSQMt5HYhEfZSAwO7BDws5KI8eAuLW4fQ5ox/GXaSqhhfZyrEPVbyNYGYyNaWJ9KWKy3uLOe3vAiBbjoZkqjdnPzMvmy8yn/zensnjWwnTnVz+XvDsAeIKju3cwFZfthZiJ9yeYnnABYR/MIal/2cFTneUJoA0EaOPRHANu2T+TpZaNalG8WkyYtWeryY12W0Nbwp9w+oc="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
