name: Release to PyPI

on:  
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: build
      run: pipx run build --sdist --wheel
    - name: publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
      run: |
        pipx install twine
        twine upload --skip-existing dist/*
